languageCode = "ja"
languageName = "日本語"
languageDirection = "ltr"
weight = 1

title = "Culthouse Liminal"

[params]
  dateFormat = "2006年1月2日"

[params.author]
  name = "ymd"
  headline = "心を奪う感覚-SENTATION- 闇にひとつ 流れてる"
  image = "img/71470873_p0_master1200.jpg"
  links = [
    { x-twitter = "https://x.com/culthouse" },
    { bluesky = "https://bsky.app/profile/culthouse.bsky.social" },
    { discord = "https://discord.com/users/culthouse" },
  ]
