languageCode = "ja"
languageName = "日本語"
languageDirection = "ltr"
weight = 1

title = "Culthouse Liminal"

[params]
  dateFormat = "2006年1月2日"

[params.author]
  name = "ymd"
  image = "img/b336079e1608d534d62f9351323b7e0b.jpg"
  links = [
    { x-twitter = "https://x.com/culthouse" },
    { bluesky = "https://bsky.app/profile/culthouse.bsky.social" },
    { discord = "https://discord.com/users/culthouse" },
  ]
