# -- Theme Options --
colorScheme = "sapphire"
defaultAppearance = "dark"
autoSwitchAppearance = true

defaultThemeColor = "#FFFFFF"

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true

fingerprintAlgorithm = "sha256"

[header]
  layout = "hybrid"
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  recentLimit = 5

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = false
  showWordCount = false

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
